source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/modules/settings.vim
source $HOME/.config/nvim/modules/mappings.vim
source $HOME/.config/nvim/modules/gruvbox.vim
source $HOME/.config/nvim/modules/nerdtree.vim
source $HOME/.config/nvim/modules/airline.vim
source $HOME/.config/nvim/modules/fzf.vim
source $HOME/.config/nvim/modules/coc.vim
source $HOME/.config/nvim/modules/emmet.vim
source $HOME/.config/nvim/modules/vimtex.vim
